version: "2"
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
#  consumer:
#    image: metrobus_consumer
#    container_name: consumer
#    ports:
#      - 8080:8080
#    environment:
#      - DB_NAME=postgres
#      - DB_USERNAME=postgres
#      - DB_PASSWORD=password
#      - METROBUS_DATA_FILENAME=metrobus_data.csv



