version: "2"
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  consumer:
    image: metrobus_consumer
    container_name: consumer
    ports:
      - 8080:8080
  api:
    image: metrobus_rest_api
    container_name: metrobus_rest_api
    ports:
      - 8000:8000



