version: "2"
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  consumer:
    build: ./data_consumer
    container_name: metrobus_consumer
    ports:
      - 8080:8080
    depends_on:
      - db
  api:
    build: ./rest_api
    container_name: metrobus_rest_api
    ports:
      - 8000:8000
    depends_on:
      - db
      - consumer



